version: '3.8'

services:
  stefanini.api:
    container_name: stefanini-api
    image: stefanini.api
    build:
      context: .
      dockerfile: Stefanini.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - JwtSettings__Secret=cdaebe2b9ac34fc5926241491204e348
      - JwtSettings__Issuer=Stefanini.com
      - JwtSettings__Audience=Stefanini
      
